packaging: `pyproject.toml` + `setuptools_scm`
insarlab/PyAPS pull request #19
Opened 2022-12-20 23:07 UTC by yunjunz

+ replace `setup.py` with `pyproject.toml` file

+ replace `version.py` with `setuptools_scm` within `pyproject.toml` file

+ requirements.txt: add packaging-related dependencies

2022-12-20 23:10 UTC, yunjunz commented
I plan to cut a release after this PR is merged, because of the `numpy` bugfix in #17.

2022-12-21 05:40 UTC, jhkennedy requested changes
Overall looks good! Couple of minor changes to consider

2022-12-21 05:40 UTC, jhkennedy commented on src/pyaps3/__init__.py
> +from importlib.metadata import PackageNotFoundError, version
`importlib.metadata` is only available for Python >=3.8. For python <3.8 you'll need the `importlib_metadata` package, which backports the functionality, and do:
```python
from importlib_metadata import PackageNotFoundError, version
```

I would just drop support for Python <3.8 and set the `requires-python = ">=3.8"` here:
https://github.com/insarlab/PyAPS/pull/19/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R13
```

2022-12-21 05:40 UTC, jhkennedy commented on src/pyaps3/__init__.py
> +__all__ = ['autoget', 'objects']
I think you'll either need:
```python
from pyaps3 import objects
from pyaps3 import autoget

__all__ = ['autoget', 'objects']
```
or:

```python
from pyaps3.objects import PyAPS
from pyaps3.autoget import ECMWFdload, MERRAdload, NARRdload

__all__ = ['PyAPS', 'ECMWFdload', 'MERRAdload', 'NARRdload']
```

`__all__` defines what'll be available with a `from pyaps3 import *` and will affect how IDE's interpret the package API. 

You may also want to include `__version__` in `__all__`.

2022-12-21 06:23 UTC, yunjunz commented on src/pyaps3/__init__.py
> +from importlib.metadata import PackageNotFoundError, version
Thank you @jhkennedy. Dropped python<3.8 as suggested.

2022-12-21 06:24 UTC, yunjunz commented on src/pyaps3/__init__.py
> +__all__ = ['autoget', 'objects']
I totally missed this. Thank you! Fixed it now.

2022-12-21 06:59 UTC, jhkennedy approved these changes

2022-12-21 07:14 UTC, merged